import {CardNames} from "./CardNames";

export const CardImages = {
  [CardNames.start]: 'https://image.flaticon.com/icons/png/512/495/495468.png',
  [CardNames.bash]: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4b/Bash_Logo_Colored.svg/1200px-Bash_Logo_Colored.svg.png',
  [CardNames.python]: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c3/Python-logo-notext.svg/1200px-Python-logo-notext.svg.png',
  [CardNames.notStonks]: 'https://i.kym-cdn.com/photos/images/facebook/001/779/895/752.jpg',
  [CardNames.stonks]: 'https://i.kym-cdn.com/entries/icons/facebook/000/029/959/Screen_Shot_2019-06-05_at_1.26.32_PM.jpg',
  [CardNames.tax]: 'https://www.pngmart.com/files/7/Tax-PNG-Transparent-Image.png',
  [CardNames.docker]: 'https://www.docker.com/sites/default/files/d8/2019-07/vertical-logo-monochromatic.png',
  [CardNames.html]: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/61/HTML5_logo_and_wordmark.svg/1200px-HTML5_logo_and_wordmark.svg.png',
  [CardNames.css]: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d5/CSS3_logo_and_wordmark.svg/1200px-CSS3_logo_and_wordmark.svg.png',
  [CardNames.js]: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/6a/JavaScript-logo.png/600px-JavaScript-logo.png',
  [CardNames.jail]: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9b/Google_Meet_icon_%282020%29.svg/2491px-Google_Meet_icon_%282020%29.svg.png',
  [CardNames.vim]: 'https://download.logo.wine/logo/Vim_(text_editor)/Vim_(text_editor)-Logo.wine.png',
  [CardNames.gcloud]: 'https://logos-world.net/wp-content/uploads/2021/02/Google-Cloud-Logo.png',
  [CardNames.vscode]: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9a/Visual_Studio_Code_1.35_icon.svg/2048px-Visual_Studio_Code_1.35_icon.svg.png',
  [CardNames.webstorm]: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/71/WebStorm_Icon.png/1200px-WebStorm_Icon.png',
  [CardNames.kubernetes]: 'https://upload.wikimedia.org/wikipedia/commons/0/00/Kubernetes_%28container_engine%29.png',
  [CardNames.java]: 'https://freepikpsd.com/file/2019/10/java-logo-png-6-Transparent-Images.png',
  [CardNames.scala]: 'https://upload.wikimedia.org/wikipedia/commons/8/85/Scala_logo.png',
  [CardNames.kotlin]: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d4/Kotlin_logo.svg/2560px-Kotlin_logo.svg.png',
  [CardNames.oneToOne]: 'https://www.kindpng.com/picc/m/133-1334294_wtf-png-wtf-png-transparent-png-wtf-png.png',
  [CardNames.redis]: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/6b/Redis_Logo.svg/2560px-Redis_Logo.svg.png',
  [CardNames.mongodb]: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/93/MongoDB_Logo.svg/2560px-MongoDB_Logo.svg.png',
  [CardNames.postgres]: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/29/Postgresql_elephant.svg/1200px-Postgresql_elephant.svg.png',
  [CardNames.ansible]: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/24/Ansible_logo.svg/1664px-Ansible_logo.svg.png',
  [CardNames.go]: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/05/Go_Logo_Blue.svg/1280px-Go_Logo_Blue.svg.png',
  [CardNames.rust]: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d5/Rust_programming_language_black_logo.svg/2048px-Rust_programming_language_black_logo.svg.png',
  [CardNames.aws]: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/93/Amazon_Web_Services_Logo.svg/1200px-Amazon_Web_Services_Logo.svg.png',
  [CardNames.cpp]: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/18/ISO_C%2B%2B_Logo.svg/306px-ISO_C%2B%2B_Logo.svg.png',
  [CardNames.goToJail]: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a5/Google_Calendar_icon_%282020%29.svg/2048px-Google_Calendar_icon_%282020%29.svg.png',
  [CardNames.bitbucket]: 'https://upload.wikimedia.org/wikipedia/commons/f/fc/Bitbucket_Logo.png',
  [CardNames.gitlab]: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e1/GitLab_logo.svg/1200px-GitLab_logo.svg.png',
  [CardNames.github]: 'https://logos-world.net/wp-content/uploads/2020/11/GitHub-Emblem.png',
  [CardNames.terrafrom]: 'https://www.andreyus.com/wp-content/uploads/2019/05/terraform1.png',
  [CardNames.clojure]: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5d/Clojure_logo.svg/2048px-Clojure_logo.svg.png',
  [CardNames.haskell]: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1c/Haskell-Logo.svg/1280px-Haskell-Logo.svg.png',

}

